# Generated by Django 4.2.23 on 2025-07-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('asking_price', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('sde', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
                ('created_on', models.DateField()),
            ],
        ),
    ]
